### ISSUE TITLE
Read bundle meta-data without loading the bundle's code into the process.

### ISSUE THREAD

**Issue by jeffdiclemente** [jeffdiclemente/CppMicroServices#2]
We want to be able to read a bundle's meta-data without loading it into the process. Doing this provides better performance when dealing with many bundles.

There are a few related technical issues to doing this which need to be solved:
- [x] Removal of most, if not all, static globals within CppMicroServices.
- [x] "Framework" and "Framework Factory" classes as a single entry point for clients to initialize CppMicroServices.
- [x] A minimal lifecycle for bundles, consisting solely of "install", "start" and "stop".
- [x] Bundles are installed first and then loaded into the process only on bundle activation.
- [x] Transition to declaring the bundle name in the bundle's manifest file.
- [x] Auto-loading needs to be either factored out into a service or modified to allow auto-installing of bundles.

**Comment by jeffdiclemente** [comment]
Merged [pull request #31](https://github.com/saschazelzer/CppMicroServices/issues/31) from saschazelzer/development. Closing.
